# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

fr:
  languageCode: fr
  contentDir: content/fr
  # [fr.params]
  #   email = "theriault.remi à courrier.uqam.ca"
  #   phone = "Quatre-trois-huit 995 7648"
  #   address = {street = "100, rue Sherbrooke Ouest", city = "Montréal", region = "Québec", postcode = "H2X 3P2", country = "Canada", country_code = "CA"}
  #   directions = "Bureau 4345 (4e étage), Pavillon Adrien Pinard. Prenez l'ascenseur jusqu'au 4e étage, tournez à gauche, encore à gauche, mon bureau sera à votre droite."

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
